default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'furni_care_development' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'furni_care_test' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
  pool: <%= ENV.fetch("TEST_DB_POOL") { 20 } %>  # Increase pool size for tests to handle concurrent operations

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'furni_care_production' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
